title: Haoran Yang's Homepage
page-top-title: Haoran Yang
top-section-bg-text: Computer Science
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Haoran Yang 2023-2025. All Rights Reserved.'
