title: Haoran Yang's Homepage
page-top-title: Haoran Yang
top-section-bg-text: Aeronautical and Astronautical Science and Technology
home-subtitle: Haoran Yang&ensp;|&ensp;杨皓然
copyright-text: '&copy; Haoran Yang 2025-2025. All Rights Reserved.'
